version: '3'

services:
  mongodb:
    container_name: support-test-mongodb
    image: mongo:latest
    volumes:
      - ./docker-config/database:/data/db:cached
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
    ports:
      - 27017:27017

  redis:
    container_name: support-test-redis
    image: redis:latest
    ports:
      - 6379:6379

  app:
    depends_on:
      - mongodb
      - redis
    container_name: support-test-app
    build:
       context: ./app
    image: support-test-node:1.0
    volumes:
      - ./app:/var/www/app:cached
    links:
      - mongodb:mongodb
      - redis:redis
    ports:
      - 3001:3001
    command: yarn start:dev

  web:
    depends_on:
      - app
    container_name: support-test-web
    build:
       context: ./web
    image: support-test-web:1.0
    volumes:
      - ./web:/var/www/web:cached
    ports:
      - 3000:3000
